# GitHub Sponsors configuration
# Uncomment and add your details when ready

# github: [YOUR_USERNAME]
# patreon: YOUR_PATREON
# open_collective: rustlette
# ko_fi: YOUR_KOFI
# tidelift: pypi/rustlette
# custom: ["https://www.buymeacoffee.com/YOUR_USERNAME"]
